nelmio_api_doc:
  documentation:
    info:
      title: Blog API
      version: 1.0.0
    paths:
      /api/users:
        get:
          summary: 'Zwraca wszystkich użytkowników'
          tags:
            - Users

        post:
          summary: 'Dodaje nowego użytkownika'
          tags:
            - Users
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                      example: my_user
                    name:
                      type: string
                      example: 'Jan'
                    surname:
                      type: string
                      example: 'Kowalski'
                    email:
                      type: string
                      example: 'email@example.com'
                    password:
                      type: string
                      example: x$%1bjb1!W
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
